searchlog = 
    EXTRACT IId:int, 
            UId:int, 
            Start:DateTime, 
            Market:string, 
            Query:string, 
            DwellTime:int, 
            Results:string, 
            ClickedUrls:string
    FROM @"/my/CosmosSampleData/SearchLog.txt"
    USING MyTsvExtractor(capitalizeStrings:true);


OUTPUT searchlog
TO @"/my/ScopeTutorial/SampleOutputs/SearchLogOutCaps.tsv" 
USING MyTsvOutputter();

