MODULE @"MyModule.module" AS M;

colors1 = 
    EXTRACT Color:string, 
            HexCode:string, 
            RGB:string, 
            Issued:String, 
            Retired:string, 
            Notes:string
    FROM @"/my/Colors.txt" 
    USING DefaultTextExtractor();

// DoNothingFunc1 will call another dynamic function called DoNothingFunc2
colors2 = M.DoNothingFunc1( input=colors1 );

OUTPUT colors2
TO @"/my/outcolors2.txt" 
USING DefaultTextOutputter();



