MODULE @"../SampleData/SampleData.module";

querylog = SampleData.QueryLog();



data =
   SELECT 
       *,
       ROW_NUMBER() OVER (PARTITION BY Vertical ORDER BY Latency) AS RowNumber,
       RANK() OVER (PARTITION BY Vertical ORDER BY Latency) AS Rank, 
       DENSE_RANK() OVER (PARTITION BY Vertical ORDER BY Latency) AS DenseRank 
FROM 
   querylog;

OUTPUT data
    TO SSTREAM @"/my/CosmosSamples/WindowingFunctions/Output/Numbering_Rows.ss"; 