// Ex3_Transform_State_and_Population.script

data1 =
    EXTRACT
        State:string,
        Population:int
    FROM @"/my/CosmosSamples/CosmosUniversity/Input/states.tsv"
    USING DefaultTextExtractor();

data2 =
    SELECT State.ToUpper() AS State, (Population/1000000.0) AS PopInMil
    FROM data1;

OUTPUT data2
    TO @"/my/CosmosSamples/CosmosUniversity/Output/output.tsv"
    USING DefaultTextOutputter();
